ProductCRUD/Models/ErrorViewModel.cs
namespace ProductCRUD.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProductCRUD/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace ProductCRUD.Models
{
    public class Product
    {
        [Key]
        public Guid ProductId { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [Required]
        [Range(1,1000)]
        public decimal Price { get; set; }

    }
}

ProductCRUD/Controllers/DemoController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProductCRUD.Controllers
{
    public class DemoController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Message = "This is ViewBag Data";

            ViewData["Info"] = "This is ViewData Data";

            TempData["Notice"] = "This is TempData Data (Survives Redirect)";
            return View();
        }

        public IActionResult TempDataDemo()
        {
            return View();
        }
        public IActionResult RedirectToTempData()
        {
            TempData["Notice"] = "This is TempData Data (Survives Redirect)";
            return RedirectToAction("TempDataDemo");
        }

    }
}

ProductCRUD/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProductCRUD.Models;
using System.Diagnostics;

namespace ProductCRUD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProductCRUD/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProductCRUD.Database;
using ProductCRUD.Models;

namespace ProductCRUD.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ProductController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            List<Product> products = _db.Products.ToList(); 
            return View(products);

        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateAsync(Product product)
        {
            if (ModelState.IsValid)
            {
                await _db.Products.AddAsync(product);
                await _db.SaveChangesAsync();
                TempData["Message"] = "Product Created Successfully!";
                TempData["MessageType"] = "success";
                return RedirectToAction("Index");
            }
            return View(product);
        }
        [HttpGet]
        public async Task<IActionResult> EditAsync(Guid productId)
        {
            var findProduct = await _db.Products.FindAsync(productId);
            if(findProduct == null)
            {
                return NotFound();
            }
            Product product = await _db.Products.FirstOrDefaultAsync(p=>p.ProductId == productId);
            return View(product);
        }
        [HttpPost]
        public async Task<IActionResult> EditAsync(Product product)
        {
            if(ModelState.IsValid)
			{
				_db.Products.Update(product);
				await _db.SaveChangesAsync();
                TempData["Message"] = "Product Edited Successfully!";
                TempData["MessageType"] = "success";
                return RedirectToAction("Index");
			}
			return View(product);
        }
        [HttpGet]
        public async Task<IActionResult> DeleteAsync(Guid productId)
		{
			var findProduct = await _db.Products.FindAsync(productId);
			if(findProduct == null)
			{
				return NotFound();
			}
			Product product = await _db.Products.FirstOrDefaultAsync(p=>p.ProductId == productId);
			return View(product);
		}
        [HttpPost]
        public async Task<IActionResult> DeleteAsync(Product product)
        {
             _db.Products.Remove(product);
            await _db.SaveChangesAsync();
            TempData["Message"] = "Product Deleted Successfully!";
            TempData["MessageType"] = "error";
            return RedirectToAction("Index");
            
        }

    }
}

ProductCRUD/Views/Demo/Index.cshtml
@{
    ViewData["Title"] = "Demo of ViewBag, ViewData and TempData";
}

<h1>@ViewData["Title"]</h1>

<p><strong>ViewBag:</strong>@ViewBag.Message</p>
<p><strong>ViewData:</strong>@ViewData["Info"]</p>
<p></p><strong>TempData:</strong>@TempData["Notice"]</p>


<a href="/Demo/RedirectToTempData">Go to TempData Demo</a>

ProductCRUD/Views/Demo/TempDataDemo.cshtml
@{
    ViewData["Title"] = "TempData Demo";
}
<h2>@ViewData["Title"]</h2>

<p><strong>TempData:</strong> @TempData["Notice"]</p>


<a href="@Url.Action("TempDataDemo", "Demo")">Refresh Page</a>

ProductCRUD/Views/Product/Create.cshtml
@model Product

@{
    ViewData["Title"] = "Create Product";
}

<h2>Create a New Product</h2>

<form asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Price" class="control-label"></label>
        <input asp-for="Price" class="form-control" type="number" step="0.01" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>


    <br />

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Create</button>
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ProductCRUD/Views/Product/Delete.cshtml
@model Product

<form method="post" asp-action="Delete">
	<input asp-for="ProductId" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete Product</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" disabled class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="Price"></label>
			<input asp-for="Price" disabled class="form-control" />
		</div>
		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<a asp-controller="Product" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

ProductCRUD/Views/Product/Edit.cshtml
@model Product

<form method="post" asp-action="Edit">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Edit Product</h2>
			<hr />
		</div>
		<input type="hidden" asp-for="ProductId" />

		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Price"></label>
			<input asp-for="Price" class="form-control" />
			<span asp-validation-for="Price" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
		<a asp-controller="Product" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

ProductCRUD/Views/Product/Index.cshtml
@model List<Product>

@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Product List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Product" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Product
            </a>
        </div>
    </div>
    <br /><br />

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Price</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model)
            {
                <tr>
                    <td width="50%">@product.Name</td>
                    <td width="30%">@product.Price</td>
                    <td width="20%">
                        <div class="btn-group" role="group">
                            <a asp-controller="Product" asp-action="Edit" asp-route-productId="@product.ProductId"
                               class="btn btn-primary btn-sm mx-1">
                                <i class="bi bi-pencil-square fs-6"></i>
                            </a>
                            <a asp-controller="Product" asp-action="Delete" asp-route-productId="@product.ProductId"
                               class="btn btn-danger btn-sm mx-1">
                                <i class="bi bi-trash-fill fs-6"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

ProductCRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductCRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductCRUD.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.11.1/font/bootstrap-icons.min.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProductCRUD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ProductCRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
<script>
    $(document).ready(function () {
        var message = '@TempData["Message"]';
        var messageType = '@TempData["MessageType"]';

        if (message) {
            if (messageType === 'success') {
                toastr.success(message);
            } else if (messageType === 'error') {
                toastr.error(message);
            } else if (messageType === 'warning') {
                toastr.warning(message);
            } else if (messageType === 'info') {
                toastr.info(message);
            }
        }
    });
</script>

</html>